version: '3'

services:
  cassandra:
      build: ./${CASSANDRA_VERSION}/
      ports:
        - '7000:7000'
        - '7001:7001'
        - '7199:7199'
        - '9042:9042'
        - '9160:9160'
      volumes:
        - './data:/var/lib/cassandra'
